import type { Config } from 'tailwindcss'

export default {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: { DEFAULT: 'var(--surface)', hover: 'var(--surface-hover)' },
        subtle: 'var(--border-subtle)',
        line: 'var(--border-line)',
        ink: { DEFAULT: 'var(--ink)', muted: 'var(--ink-muted)', faint: 'var(--ink-faint)' },
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
          active: 'var(--primary-active)',
          fg: 'var(--primary-fg)',
          soft: 'var(--primary-soft)',
          muted: 'var(--primary-muted)',
        },
        success: { DEFAULT: 'var(--success)', soft: 'var(--success-soft)' },
        warning: { DEFAULT: 'var(--warning)', soft: 'var(--warning-soft)' },
        danger: { DEFAULT: 'var(--danger)', soft: 'var(--danger-soft)' },
        info: { DEFAULT: 'var(--info)', soft: 'var(--info-soft)' },
        status: {
          'open': { soft: 'var(--status-open-soft)', fg: 'var(--status-open-fg)' },
          'in_progress': { soft: 'var(--status-in_progress-soft)', fg: 'var(--status-in_progress-fg)' },
          'resolved': { soft: 'var(--status-resolved-soft)', fg: 'var(--status-resolved-fg)' },
          'verified': { soft: 'var(--status-verified-soft)', fg: 'var(--status-verified-fg)' },
          'closed': { soft: 'var(--status-closed-soft)', fg: 'var(--status-closed-fg)' },
        },
        priority: {
          'low': { soft: 'var(--priority-low-soft)', fg: 'var(--priority-low-fg)' },
          'medium': { soft: 'var(--priority-medium-soft)', fg: 'var(--priority-medium-fg)' },
          'high': { soft: 'var(--priority-high-soft)', fg: 'var(--priority-high-fg)' },
          'critical': { soft: 'var(--priority-critical-soft)', fg: 'var(--priority-critical-fg)' },
        },
        approval: {
          'draft': { soft: 'var(--approval-draft-soft)', fg: 'var(--approval-draft-fg)' },
          'under_review': { soft: 'var(--approval-under_review-soft)', fg: 'var(--approval-under_review-fg)' },
          'approved': { soft: 'var(--approval-approved-soft)', fg: 'var(--approval-approved-fg)' },
          'approved_with_comments': { soft: 'var(--approval-approved_with_comments-soft)', fg: 'var(--approval-approved_with_comments-fg)' },
          'changes_requested': { soft: 'var(--approval-changes_requested-soft)', fg: 'var(--approval-changes_requested-fg)' },
          'rejected': { soft: 'var(--approval-rejected-soft)', fg: 'var(--approval-rejected-fg)' },
          'superseded': { soft: 'var(--approval-superseded-soft)', fg: 'var(--approval-superseded-fg)' },
        },
        health: {
          green: 'var(--health-green)',
          yellow: 'var(--health-yellow)',
          red: 'var(--health-red)',
        },
        discipline: {
          architectural: 'var(--discipline-architectural)',
          structural: 'var(--discipline-structural)',
          electrical: 'var(--discipline-electrical)',
          plumbing: 'var(--discipline-plumbing)',
          fire_safety: 'var(--discipline-fire_safety)',
          interior: 'var(--discipline-interior)',
          landscape: 'var(--discipline-landscape)',
          construction: 'var(--discipline-construction)',
          documentation: 'var(--discipline-documentation)',
          client_coordination: 'var(--discipline-client_coordination)',
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['var(--font-body)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: { DEFAULT: 'var(--radius)', lg: 'var(--radius-lg)' },
      boxShadow: { sm: 'var(--shadow-sm)' },
      borderColor: { DEFAULT: 'var(--border-line)' },
    },
  },
  plugins: [],
} satisfies Config
